### ISSUE TITLE
Add nice support for being logged into multiple Zulip servers at the same time

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-electron#1]

**Comment by geeeeeeeeek** [comment]
@timabbott Claimed. I had the same idea for my `electronic-wechat`. This won't be easy to do and will take some time. Hope to get it done before 21 March.

**Comment by akashnimare** [comment]
@geeeeeeeeek basically we want to add something like this - 
<img src="https://raw.githubusercontent.com/Thomas101/wmail/master/.github/screenshot.png"/>
https://github.com/Thomas101/wmail
Let me know if you need any help in this.

**Comment by geeeeeeeeek** [comment]
Understand. Will have a try on the weekend.

**Comment by geeeeeeeeek** [comment]
Update: There will a few changes to our current architecture.

1. [Front-End] For now we use `new-domain` to open a new window for one Zulip server. To support multiple servers, we will open a single-instance browser window (like the screenshot attached before). This should be a local webpage which contains a `WebView`. Each time the user switch to a new server, the webview will be redirected to a new domain.
2. [Back-End] We need to change the structure of how servers are stored in the local environment. This should be represented as an array of JSON objects, each containing the name, domain, credentials of a server. The array should be in order and remembers the last active index.

Estimated time to complete: 27 March.

In the future, we may also consider:
1. Introducing a more complicated server management UI in the preference panel.
2. Multiple servers online at the same time. So that users can receive notifications from different servers.
3. Seamless loading when switching between servers.

 Estimated time to complete: During GSoC.

**Comment by Lplenka** [comment]
@geeeeeeeeek I wanted to work on this feature as a part of my GSoC Project. It would be nice if you could be here to guide me for this task during GSoC.

**Comment by geeeeeeeeek** [comment]
@Lplenka Sure. I am working on the basic functionalities and sure there will be much to improve after.

**Comment by Lplenka** [comment]
Thank you @geeeeeeeeek

**Comment by Lplenka** [comment]
> @geeeeeeeeek I wanted to work on this feature as a part of my GSoC Project. It would be nice if you could be here to guide me for this task during GSoC.

@timabbott  @akashnimare 
 This issue is first phase of GSoC proposal. Forgot to gave a link to my proposal prototype earlier here. 
[https://github.com/Lplenka/zulip-electron/tree/Multiple_Server](https://github.com/Lplenka/zulip-electron/tree/Multiple_Server)
Will work on this issue more thoroughly and improve minute UI and backend requirements in summer.

**Comment by akashnimare** [comment]
This feature has been added and will be pushed in next release.

![image](https://user-images.githubusercontent.com/2263909/27002144-f034f8fa-4df6-11e7-802e-6486dfd82b0a.png)

![1f384d62-493a-11e7-9015-0e78dfb03742](https://user-images.githubusercontent.com/2263909/27002206-1ba93a08-4df9-11e7-8d5e-2682dcc6b039.png)

(it's still in early phase and need some refinements)

**Comment by akashnimare** [comment]
This feature has been added in https://github.com/zulip/zulip-electron/commit/68c90434b305e107b5bf1e2858f6a05b63a47f07. Thanks, @geeeeeeeeek 💪
