### ISSUE TITLE
chat.zulip.org not set as default

### ISSUE THREAD

**Issue by anirudhjain75** [zulip/zulip-electron#100]
- `Operating System`
Ubuntu 14.04
- `Clear steps to reproduce the issue`
Run the electron app and click on `connect` without typing anything on the link box
- `Expected outcome`
It must connect to Zulip development chat i.e. chat.zulip.org by default
- `Relevant error messages and/or screenshots`
![screen shot 2017-01-13 at 11 36 46 pm](https://cloud.githubusercontent.com/assets/14249589/21940784/e1cd8c84-d9eb-11e6-92d0-8f0ecc5c2150.png)

**Comment by timabbott** [comment]
@anirudhjain75 why should it connect to chat.zulip.org by default?  The vast majority of Zulip users do are not part of the Zulip development community and do not use chat.zulip.org.

(I think we probably do want to remove or change the placeholder to be more clear).

**Comment by anirudhjain75** [comment]
Yeah it would be better to remove `chat.zulip.com` from the view and make it something like `enter the server URL`

**Comment by akashnimare** [comment]
@anirudhjain75 it's just an example. I think the placeholder is fine although we could change the title from `Login to Zulip Server` to `Enter your Zulip host/server URL` to make it more clear. 
@timabbott what do you think?

**Comment by anirudhjain75** [comment]
I guess that would be better, but what about the confusion caused due to chat.zulip.org

**Comment by timabbott** [comment]
@akashnimare I think changing the title to perhaps "Enter your Zulip server login URL" is definitely helpful (Slack users the term "login URL" which I think is helpful for this context).  I would also consider changing the placeholder to "E.g. chat.zulip.org" to make clear that entering nothing will not connect to chat.zulip.org (since that is a common pattern inthis sort of input field).

**Comment by timabbott** [comment]
@borisyankov @neerajwahi we should probably use the same text in the "enter the server" login prompt on the mobile app as here; what do you think the right choice is?

**Comment by borisyankov** [comment]
Placeholders should not look like real data.
On Web you can have labels, on mobile the trend is to have the label as placeholder.
In that case the placeholder should be 'Server URL' and not a valid server URL.

The shorter and still clear the text is, the better.

'Zulip Server' is ambiguous. 'Server Address' or 'Server URL' is clear.

**Comment by neerajwahi** [comment]
I agree that we should avoid placeholders that look like real data (because it's easily confused with a default value).

I think we could just write 'URL' as the placeholder. If the title is 'Login to Zulip Server' that should be pretty obvious and discoverable. We should make sure it's fairly forgiving though (and automatically prepend 'https://' if omitted, for example)

**Comment by akashnimare** [comment]
@timabbott going with `Enter your Zulip Server URL` for the title. For placeholder, I think `demo.zulip.chat` or just `Server URL` would be fine. @neerajwahi 'https://' is automatically added to URL :)

**Comment by akashnimare** [comment]
Fixed in https://github.com/zulip/zulip-electron/commit/063799a05396ff90317ae00b43e5eb5145abcb96.
