### ISSUE TITLE
Add an option to hide the tray icon

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-electron#104]
I've gotten feedback from a few users that they would appreciate the ability to disable the Mac OS menu bar item for Zulip to keep it uncluttered.

**Comment by geeeeeeeeek** [comment]
I've sent a PR to toggle the tray icon.

![screen shot 2017-03-05 at 12 53 01 am](https://cloud.githubusercontent.com/assets/7262715/23580520/8c411cde-013e-11e7-9f77-ce2ef7429191.png)

However, in the future, I think we should have a centralized Preference pane to collect all these settings. So that users won't bother to repeat these actions as they restart the app.

**Comment by timabbott** [comment]
Yeah, agreed, a centralized preference pane is a good model.

@geeeeeeeeek have you checked out the old/legacy desktop app that was written in QT/webkit available from https://chat.zulip.org/apps/?  It had a few menu items, which may be useful context for you in thinking about this.

**Comment by geeeeeeeeek** [comment]
Didn't know there were a legacy app. I will look into that. But we are going to do the Preferences pane, there better be a ux designed.

**Comment by geeeeeeeeek** [comment]
@timabbott Electron does not provide a way to integrate a native Preference pane. We need to write a local web app (or web page) to do that. Maybe in another PR. I would suggest adding the option to the menu for now.

<img width="519" alt="screen shot 2017-03-05 at 4 14 16 pm" src="https://cloud.githubusercontent.com/assets/7262715/23585663/d2179604-01be-11e7-8911-c7c38fb1f091.png">

**Comment by akashnimare** [comment]
> I would suggest adding the option to the menu for now.

Make sense. Merged #122

**Comment by akashnimare** [comment]
Moving this discussion to https://github.com/zulip/zulip-electron/issues/123
