### ISSUE TITLE
Attachments should open in-browser

### ISSUE THREAD

**Issue by jjst** [zulip/zulip-electron#13]
Looks like I found an exception to the exception in #11 :smile: 

When opening an attachment, e.g. an image, in the zulip electron app, it opens in-app, and then there's no way to go back to the chat window. I have to close/reopen the app.

Maybe only links to streams/topics ought to open in-app?

**Comment by timabbott** [comment]
I think the correct rule is probably something about /# links open in-app, but not other things hosted on the site.

**Comment by akashnimare** [comment]
I am using ubuntu 14.04 and all the attachments are opened in a default browser.
Have a look -

![attachments](https://cloud.githubusercontent.com/assets/2263909/16346797/d71ba34a-3a66-11e6-89b4-6fe3a68419fd.gif)

I think it should work this way only. @timabbott What do you think? @jjst can you upload a gif of your problem here?

**Comment by timabbott** [comment]
Yeah that video looks pretty reasonable to me.

**Comment by akashnimare** [comment]
May be there is bug on OSX when opening this kind of links.

**Comment by jjst** [comment]
For the life of me I can't reproduce the issue anymore. I don't know what changed! The exact same scenario I used and tested on this morning now. I guess you can close, I'll reopen with a proper screencast if I stumble on the issue again. Sorry for the trouble!

(FWIW I'm on Ubuntu as well, 16.04)

**Comment by akashnimare** [comment]
No worries :smile_cat:. I am updating the repo daily so please keep your local zulip-electron repo sync :smiley:.
