### ISSUE TITLE
Change install instructions: Ubuntu/Debian users shouldn't install nodejs-legacy

### ISSUE THREAD

**Issue by brainwane** [zulip/zulip-electron#135]
I'm on Linux Mint 18 ("Sarah") (based on Ubuntu Xenial). I installed `nodejs-legacy` per the README instructions, through my usual package manager. When I run `nodejs --version` I see I'm on v4.2.6. We require node >= v6.3.1. We need to give people instructions for installing Node.js & npm that won't give them old versions of Node.

**Comment by timabbott** [comment]
Yeah, we should just recommend using nvm (or really, script using it) as part of the installer.

There's some code in `tools/install-node` in zulip.git we may be able to reuse.

Almost nobody has a modern node/npm shipped with their distro.

**Comment by akashnimare** [comment]
I have just pointed to nvm repo to install nodejs. Is it good enough or we should write it in details like-

For the most recent LTS (the 6.x.x branch), use:
```sh
curl -sL https://deb.nodesource.com/setup_6.x.x | sudo -E bash -
```
The PPA will be added to your configuration and your local package cache will be updated automatically. After running the setup script from nodesource, you can install the Node.js package :
```sh
sudo apt-get install nodejs

**Comment by timabbott** [comment]
I think we should update the installation instructions (or provide a script) that Just Works, so that installing is super easy for folks who want to test out the development version.

I'm not sold on the PPA approach, though, since users might be relying on a specific version of the system node, whereas with NVM, we can avoid disrupting users' existing setup.

**Comment by akashnimare** [comment]
Development guide has been updated. Merging this into #145.
