### ISSUE TITLE
Add Debian installer to a PPA

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-electron#3]

**Comment by akashnimare** [comment]
@timabbott This could be easily done. Once our app is stable we will build it for all the platform.

**Comment by sahildua2305** [comment]
@akashnimare I can help with this. Are we ready to package for debian?

**Comment by akashnimare** [comment]
@sahildua2305 all the installers are ready. I'm holding this because of https://github.com/zulip/zulip-electron/issues/74 😭 . I'll be pushing all the packaging/building scripts to the main repo, once **auto-update** feature is added.

**Comment by timabbott** [comment]
@akashnimare for Debian packages with a PPA, there's an existing automatic update setup (namely apt), so I don't think we need to delay putting these in a PPA on account of auto-update.  We have I have an existing Launchpad organization for the Zulip project that we can use for this.

**Comment by akashnimare** [comment]
@timabbott for auto-updating, we have two options here -

1.  Add deb to PPA as you suggested (linux-only)
2. Use Electron way - which is  [electron-builder](https://github.com/electron-userland/electron-builder) or [electron-update](https://github.com/evolvelabs/electron-update) (cross-platform)

I'm trying to implement the second one. This works kind of smooth and cross-platform. It shows a popup if the update is available and downloads it in the background.

Since the second option is not ready yet let's go with the first one. I'll be adding .deb to our release page and from there you can add it to PPA. Let's see if it works.

**Comment by timabbott** [comment]
Cool, @akashnimare I think you could focus on the Electron way and @sahildua2305 could focus on building a Debian packaging (basically just writing a proper debian/ directory).  I have a lot of experience doing Debian packaging (used to maintain over 100 packages) so I'm happy to review the debian packaging work.

**Comment by sahildua2305** [comment]
@akashnimare So the debian packaging is already done and I need to format that into a proper debian/ directory to make it ready for PPA. Is that right?

**Comment by akashnimare** [comment]
@sahildua2305 I got this 👍 .

**Comment by akashnimare** [comment]
Progress is happening here: [electron-builder](https://github.com/zulip/zulip-electron/tree/electron-builder).

**Comment by akashnimare** [comment]
This feature is added in the latest build i.e. [v0.5.1](https://github.com/zulip/zulip-electron) 😄 .

**Comment by timabbott** [comment]
@zulipbot claim 
(testing)

**Comment by timabbott** [comment]
@zulipbot claim (testing again)

**Comment by timabbott** [comment]
success.
