### ISSUE TITLE
Notifications when Electron/Zulip in foreground.

### ISSUE THREAD

**Issue by GervaisdeM** [zulip/zulip-electron#44]
I still get notifications from the Desktop app when I am currently using it. IMO, notifications should be muted while the app is in the foreground.
- macOS Sierra

**Comment by akashnimare** [comment]
I have not touched the notifications feature yet. We could change it according to our need once we implement notifications feature using [node-notifier](https://www.npmjs.com/package/node-notifier) or with some module.

**Comment by akashnimare** [comment]
It's possible to mute notifications when app is in foreground. Here is good read -
https://github.com/electron/electron/issues/5983

**Comment by akashnimare** [comment]
@GervaisdeM Could you please test it again?

**Comment by GervaisdeM** [comment]
I'm running the latest master branch. I'll keep an eye out for this.

**Comment by akashnimare** [comment]
@GervaisdeM can you check it again and see if it's fixed 🤔

**Comment by GervaisdeM** [comment]
Hey @akashnimare 

It's still happening... You can see in the screenshot below that Electron is in the frontmost app and that I am still getting notifications for messages. I've read and replied to some of them, but the notification says "4 messages from Gail..."

![screen shot 2017-02-15 at 9 20 06 am](https://cloud.githubusercontent.com/assets/963514/22976274/76795f10-f360-11e6-87f3-a505f9a7d966.png)

**Comment by akashnimare** [comment]
@GervaisdeM thanks for the update, I'll check it out.

**Comment by GervaisdeM** [comment]
This may or may not be related to what you are trying to sort out, but now I am not getting the OS notifications at all and I am getting the *built-in* type. I only notice them when the app is in the foreground.

<img width="944" alt="screen shot 2017-02-22 at 9 32 42 pm" src="https://cloud.githubusercontent.com/assets/963514/23262452/2074c31e-f9b1-11e6-9c21-92919568083f.png">

**Comment by akashnimare** [comment]
@GervaisdeM I confirm this bug. Let me see what's wrong.

**Comment by akashnimare** [comment]
@GervaisdeM can you check it again? Notifications should work now 😅

**Comment by GervaisdeM** [comment]
@akashnimare notifications are back.  👍

**Comment by akashnimare** [comment]
@GervaisdeM nice. Thanks for reporting it.

**Comment by chiragjn** [comment]
So , I have been spamming myself from another account for a while now. This is what I think:

Notifications received in the foreground makes sense when received message is not in current stream/ focus. This works as expected.

Zulip's notifications.js would send notification for any unread messages, which means even if the app is in foreground and message is received in focused stream but stays unread (maybe because scroll is not at the bottom) triggers a notification.

So if the app fails to set "read" status on message before notifications.js script checks for it, notification will be triggered anyway. This can happen on browser as well and this occurs rarely in my spam experiments.

A good way to notify for current focused stream/dm would be to show a label type snackbar "New messages below" instead of creating a Notification, but that is work for zulip server repository, not here.

**Comment by timabbott** [comment]
I believe the issue about correct (but not well documented, perhaps) behavior.  In Zulip web (and thus also desktop), we trigger desktop notifications when:
* The settings are enabled
* A new message arrives while either (1) Zulip window is not in focus or (2) the new message would be arriving on-screen.  "off-screen" covers both the case where you're in a different narrow and the case where you're in the correct narrow, but scrolled up.  
* This is implemented in the webapp through logic around automatically marking the message as read if the window is in focus and the new message arrives on-screen.

@GervaisdeM @chiragjn does that make sense and sound consistent with what you experienced?
