### ISSUE TITLE
Error opening Zulip darwin build

### ISSUE THREAD

**Issue by jedahan** [zulip/zulip-electron#50]
#### Summary

Zulip doesn't open when bundled as an application on osx.

#### Steps to reproduce

On OSX 10.10, create a new npm script in package.json:
`"build-osx": "electron-packager . --out=dist --platform=darwin --arch=x64 --
  app-version=$npm_package_version --asar --overwrite"`

then run `npm run-script build-osx`

one that finishes, `open dist/Zulip-darwin-x64/Zulip.app`

#### Expected behavior

Zulip starts with no error

#### Observed behavior

<img width="532" alt="screen shot 2016-08-14 at 12 46 31 pm" src="https://cloud.githubusercontent.com/assets/32407/17650492/58b0b142-621d-11e6-9b38-3d4a750d4e8f.png">

#### Possible fixes

Just a guess, but maybe Electron doesn't have filesystem level access? Depending on what node-json-db is used for, localStorage might be enough.

**Comment by akashnimare** [comment]
@jedahan localStorage is good for small db based app. I am guessing in long run we'll have to handle more data and will be needing a good db framework. As of now node-json-db looks good. We might switch to [nedb](https://github.com/louischatriot/nedb) since it's built for electron only. Btw The above error occurred because of wrong file path given to node-json-db. It's fixed here - 
https://github.com/zulip/zulip-electron/blob/master/app/main/index.js#L16

**Comment by akashnimare** [comment]
Since build script and node-json-db error fixed we won't need #51.
